require("davidkhanks.plugins-setup")
require("davidkhanks.core.options")
require("davidkhanks.core.keymaps")
require("davidkhanks.core.colorscheme")
require("davidkhanks.plugins.comment")
require("davidkhanks.plugins.gitsigns")
require("davidkhanks.plugins.harpoon")
require("davidkhanks.plugins.nvim-tree")
require("davidkhanks.plugins.lualine")
require("davidkhanks.plugins.nvim-toggler")
require("davidkhanks.plugins.dressing")
require("davidkhanks.plugins.telescope")

-- require("davidkhanks.plugins.nvim-cmp")
-- require("davidkhanks.plugins.lsp.mason")
-- require("davidkhanks.plugins.lsp.lspsaga")
require("davidkhanks.plugins.lsp.lsp-zero")
-- require("davidkhanks.plugins.lsp.lspconfig")

require("davidkhanks.plugins.autopairs")
require("davidkhanks.plugins.treesitter")
